// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knowhpqkzbkxpveewkvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtub3docHFremJreHB2ZWV3a3ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2ODE2NzgsImV4cCI6MjA2NTI1NzY3OH0.pq2aZ6Cr65AV2CLzDRevu2ECz5d15dq__kG5UjU0BAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);